# CREDS

PM_URL = ""
PM_API_TOKEN_ID = ""
PM_API_TOKEN_SECRET = ""
PM_TLS_INSECURE = true

# VM SETTINGS
VM_TARGET_NODE = "prx"
VM_TOTAL = 1
VM_NAME = "docker"
VM_TEMPLATE = "jalanbuntu"
VM_START_ID = 820
VM_CPU_CORES = 2
VM_CPU_SOCKETS = 2
VM_RAM = 2048
VM_FULL_CLONE = true


CI_USER = ""
CI_PASSWORD = ""
SSH_PUBKEY = ""
